name: Wollphy Films
favicon: null
layout_spectrum: 0
typography_spectrum: 0.03294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#606060'
    - '#7c7c7c'
    - '#aeaeae'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
